### ISSUE TITLE
syntax highlighting vanished

### ISSUE THREAD

**Issue by jonathanlilly** [Bramas/texiteasy#13]
On El Cap, syntax highlighting has vanished and won't come back.  Also, can't find any themes.  Not sure why.  Re-installing doesn't help.

**Comment by jonathanlilly** [comment]
This was solved by locating the /Users/xx/Library/Application Support/Texiteasy folder on another machine and manually copying it.  Apparently, the themes in the original folder had gone missing, for some unknown reason.

**Comment by jonathanlilly** [comment]
I believe I know what happened here.  Command-T is the command that opens the themes folder, and this is also command that runs the build in TexShop.  I must have done this out of habit, then somehow accidentally highlighted and deleted the themes when the window popped open.   Curious if others mix up these bindings as well.

**Comment by Bramas** [comment]
Hi, thanks for the feedback, and the resolution of the issue :)

Maybe opening the theme folder should not have a shortcut by default as it is not something we do everyday.

Thanks again for keeping me informed of why this happened, this avoid me to debug a hard to repreduce  bug.

**Comment by jonathanlilly** [comment]
No problem.  Thanks for the great program!  It's the best LaTex editor for
a Mac, in my opinion.  --- J
