### ISSUE TITLE
size of the displayed pdf

### ISSUE THREAD

**Issue by mhtm** [Bramas/texiteasy#18]
Is there a way to resize the displayed pdf? I can't find any and on my screen it is so small that it's unreadable. It would be nice to have a "fit width" option in the pdf viewer.

**Comment by Bramas** [comment]
Yes, you can use Ctrl + mouse Wheel on windows and linux.
On mac you can either use Cmd + mouse Wheel or the resizing gesture.

**Comment by mhtm** [comment]
Thanks!
