### ISSUE TITLE
How to trigger forward search?

### ISSUE THREAD

**Issue by caoyeacy** [Bramas/texiteasy#22]

**Comment by Bramas** [comment]
sorry for the delay.
by forward search you mean searching in the tex source file in a backward manner? (-> just Ctrl + F and click with your mouse on the left arrow)
or you mean synch the source with a position on the pdf? (-> Ctrl + click on the pdf)

(replace Ctrl with Cmd if you're on a Mac)

**Comment by caoyeacy** [comment]
just like the function of  ctrl+L J in Latextool of SublimeText, sync the pdf to the selected line in the tex source

**Comment by Bramas** [comment]
It's Ctrl+D in TexitEasy, its configurable in the options (however its called "See Pdf", don't remember why I called it this way ^^)
