### ISSUE TITLE
black preview

### ISSUE THREAD

**Issue by billyhill** [Bramas/texiteasy#3]
Sometimes the preview just went black after STRG+B but no error is shown.

Edit: PDF file itself is fine.

**Comment by Bramas** [comment]
Hello,
Thanks for your feedback. Did you try with the last version 0.20.0? because I fixed an issue in this version: when updating the pdf on the viewer, a link request were done on the outdated version of the pdf. maybe it is related.

**Comment by billyhill** [comment]
Yes, i'm using the latest version. However, I was able to solve the problem by copying the tex code to a new file.

PS: I really like texiteasy. It's so clean and fast. =D

**Comment by Bramas** [comment]
OK maybe the encoding of the first file was not detected properly. Let me know if you have another bug.
I use texiteasy every day so I really try to make it stable, fast and clean. Really happy you like it to :)
