### ISSUE TITLE
don’t require TeX Live installed on Linux

### ISSUE THREAD

**Issue by ousia** [Bramas/texiteasy#39]
Hi @Bramas,

I have tried to install _TexitEasy_ on my Fedora 25 machine, but it requires me to install Tex Live from the Fedora packaging system.

I think this is an awful default requirement, because many of us have TeX Live installed directly (updates work much easier). Or at least, with that requirement, this is preventing users from having TL from <https://www.tug.org/texlive/>.

In my particular case, I would like to test _TextitEasy_ to see whether it fits for ConTeXt. But I wonder whether the program is still being developed.

Many thanks for your help.

**Comment by Bramas** [comment]
Hi @ousia ,
Thank you for all your feedback!
for the texlive dependency, I may defined it as optional I think
I you see, texiteasy is not heavily maintained, but I used it every day (almost) at work and I try to improve it when I have time. I would be happy to receive PR and will do my best to deploy new versions.

**Comment by ousia** [comment]
PR accepted, so closing this issue.
