### ISSUE TITLE
OK instead of Submit

### ISSUE THREAD

**Issue by ousia** [Bramas/texiteasy#42]
At least, I have seen it in the preferences:

![more-themes](https://user-images.githubusercontent.com/203767/28995059-b646fcd8-79de-11e7-8692-b55305bc89cf.png)

Is there any reason to use Submit instead the standard OK?

(I could make a pull request with the fix to it, but first, I need to know whether development will be active again.)

**Comment by Bramas** [comment]
no reason 😃
