### ISSUE TITLE
path to binaries should be loaded before system paths

### ISSUE THREAD

**Issue by ousia** [Bramas/texiteasy#47]
I have the following configuration for compilation in _TexitEasy_:

![path-binaries](https://user-images.githubusercontent.com/203767/28998355-fc51ce84-7a28-11e7-9907-adf4b8f56e7d.png)

I have _TeX Live_ installed and a portable ConTeXt distribution (_ConTeXt Suite_), which provides the latest released version of ConTeXt.

To make the latest version of ConTeXt available on my computer work, I have to load the path to binaries first. Otherwise, ConTeXt from _TeX Live_ will be chosen.

I may load the ConTeXt path to latest version with:

```
source ~/context/tex/setuptex
```

The other way is to set the path to binaries (such as I do in _TeXworks_):

```
~/context/tex/texmf-linux/bin/
```

As you may see, this is what I have done in the configuration dialog.

But I’m afraid that this path is taken into account only if the system contains no other path.

It also makes sense to specify this path to be loaded before any system path. This would make possible to use portable TeX distributions with _TeXitEasy_.

**Comment by Bramas** [comment]
If the path in the settings is given, it is always appended to the system path (https://github.com/Bramas/texiteasy/blob/master/source/builder.cpp#L97)
However for your case, it should be prepended otherwise the default tex bin will be used.
I think it is okay to always preprend the path given in the settings, it seems logical

**Comment by ousia** [comment]
@Bramas, I cannot code, but the patch was so simple that I provide it.

Check it before merging it.
