### ISSUE TITLE
Suspect Virus - Win32/Elevate.A Potentially Unsafe

### ISSUE THREAD

**Issue by Syenta** [Bramas/texiteasy#57]
Hi,

I've just scanned your latest offering of TexitEasy on VirusTotal and it produce a Win32/Elevate.A Potentially Unsafe warning.

Should I be worried? Here is a link to the scan result - https://www.virustotal.com/gui/file/8bba0c1a8933489c1d06962e576e5a0a130d2f85107fd1d17c121c13b662b909/detection

Hope it helps.

**Comment by bertvandepoel** [comment]
I'm afraid this piece of software isn't really being maintained anymore and can't even be compiled on modern linux installations. I'm not sure if it's a good idea getting used to texiteasy, since it's unsure it will continue to run in the future.

**Comment by Syenta** [comment]
Thanks for getting back in touch about this much appreciated.
