### ISSUE TITLE
segmentation fault after clicking apply twice in Preferences

### ISSUE THREAD

**Issue by plusInfinity** [Bramas/texiteasy#6]
Hi, thanks for investing your time into texiteasy. The concept seems quite promising. Found a bug during testing: if I click apply in preferences twice I get a segmentation fault. Not a serious one, but still...

Also the main issue which stops me from using it right now is that PDF viewer has hard-coded zoom ratio, which makes small and hard to read on a HIDPI screen.

**Comment by Bramas** [comment]
Thanks for the feedback, i will investigate the error soon.

For the zoom, you can zoom in or out with Ctrl+mouse wheel. I know i need to add a quick help window at the first launch to explain all the hidden features.
